---
before_install:
  - sudo apt-get install libextractor-dev
  - gem update --system
  - gem install bundler -v "~> 2.0"
language: ruby
cache:
  - bundler
rvm:
  - 2.6
  - 2.7
  - jruby
matrix:
  allow_failures:
    - rvm: jruby
script: bundle exec rake spec
